### ISSUE TITLE
the link to the your_tensorflow_model.tar.gz seems dead

### ISSUE THREAD

**Issue by lionzheng10** [alex-lechner/Traffic-Light-Classification#1]
Is there some way to download this file? I searched in google, but find nothing.

**Comment by alex-lechner** [comment]
Which link to you mean? This one `wget http://download.tensorflow.org/models/object_detection/your_tensorflow_model.tar.gz`?

You have to replace `your_tensorflow_model` in the URL with the model you want to retrain, this can be e.g. `faster_rcnn_inception_v2_coco_2018_01_28` or `ssd_inception_v2_coco_2017_11_17`. In my project I use SSD Inception V2 so to download this model you need to replace `your_tensorflow_model` with `ssd_inception_v2_coco_2017_11_17` like so: `wget http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz`
