### ISSUE TITLE
ValueError: No op named NonMaxSuppressionV3 in defined operations.

### ISSUE THREAD

**Issue by thejerrytan** [alex-lechner/Traffic-Light-Classification#2]
Hey Alex, thanks so much for a wonderful writeup.

I downloaded the model from tensorflow/models repo and trained ssd_inception_v2_coco on your simulator dataset.

I had to train on TF1.10 because otherwise i would get some error about axis dimension not in [0,0) in the hard negative miner class. Someone filed this issue on tensorflow/models repo and the fix was to train on v1.8 and above.

After training, i exported it out on TF1.4, now i am running the imported graph on TF1.3 on the simulator and this is what I get:

```
Traceback (most recent call last):
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 179, in <module>
    TLDetector()
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 46, in __init__
    self.light_classifier = TLClassifier(True)
  File "/capstone/ros/src/tl_detector/light_classification/tl_classifier.py", line 25, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named NonMaxSuppressionV3 in defined operations.
```

Wondering if u know the fix for this?

**Comment by alex-lechner** [comment]
Hey,

I guess you're talking about [#5111](https://github.com/tensorflow/models/issues/5111), right? I haven't used TF 1.8 or above for this project. I can only advise you to train your model with TF 1.4 AND **use an older pre-trained model from the model zoo** e.g. [SSD Inception V2 Coco (17/11/2017)](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz) (look at the date). It seems that NonMaxSuppressionV3 is a new operations which is introduced in TF 1.8, older versions seem to use NonMaxSuppression and NonMaxSuppressionV2.

If you want to make sure that your model form the model zoo won't interfere with your tensorflow version 1.4 then head to the tensorflow repository and change the branch from _branch: master_ to [tag: v1.4.0](https://github.com/tensorflow/models/tree/v1.4.0)

I hope this helps. I wish you good luck for the capstone project! 🙂

**Comment by martinezedwin** [comment]
Did you ever get a solution for this? Having similar issue.

**Comment by alex-lechner** [comment]
Do you guys have to work with a version > TF1.4? If so, which one is it?

**Comment by kenny1323** [comment]
My experience.
I am using a library named POSENET.
This library automatically download some model files like model-mobilenet_v1_101.pb and model-mobilenet_v1_101.ckpt.meta into a directory named _models.
I just clean the 2 directories: _models and _pycache_.
So Posenet downlod them again.
My environment: ubuntu18 (host), docker; ubuntu18 (guest); python3.6.9; tensorflow1.4.0
